source 'https://github.com/CocoaPods/Specs.git'

target 'PhotoSubmitter', :exclusive => true do
  pod "FBNetworkReachability", :git => "https://github.com/dev5tec/FBNetworkReachability.git"
  pod "PhotoSubmitter", :path => "../"
  pod "PhotoSubmitter/Facebook", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PhotoSubmitter", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
